// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/deliveryagency"
	"backend/ent/predicate"
	"backend/ent/product"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeliveryAgencyQuery is the builder for querying DeliveryAgency entities.
type DeliveryAgencyQuery struct {
	config
	ctx          *QueryContext
	order        []deliveryagency.OrderOption
	inters       []Interceptor
	predicates   []predicate.DeliveryAgency
	withProducts *ProductQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeliveryAgencyQuery builder.
func (daq *DeliveryAgencyQuery) Where(ps ...predicate.DeliveryAgency) *DeliveryAgencyQuery {
	daq.predicates = append(daq.predicates, ps...)
	return daq
}

// Limit the number of records to be returned by this query.
func (daq *DeliveryAgencyQuery) Limit(limit int) *DeliveryAgencyQuery {
	daq.ctx.Limit = &limit
	return daq
}

// Offset to start from.
func (daq *DeliveryAgencyQuery) Offset(offset int) *DeliveryAgencyQuery {
	daq.ctx.Offset = &offset
	return daq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (daq *DeliveryAgencyQuery) Unique(unique bool) *DeliveryAgencyQuery {
	daq.ctx.Unique = &unique
	return daq
}

// Order specifies how the records should be ordered.
func (daq *DeliveryAgencyQuery) Order(o ...deliveryagency.OrderOption) *DeliveryAgencyQuery {
	daq.order = append(daq.order, o...)
	return daq
}

// QueryProducts chains the current query on the "products" edge.
func (daq *DeliveryAgencyQuery) QueryProducts() *ProductQuery {
	query := (&ProductClient{config: daq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := daq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := daq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deliveryagency.Table, deliveryagency.FieldID, selector),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, deliveryagency.ProductsTable, deliveryagency.ProductsColumn),
		)
		fromU = sqlgraph.SetNeighbors(daq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DeliveryAgency entity from the query.
// Returns a *NotFoundError when no DeliveryAgency was found.
func (daq *DeliveryAgencyQuery) First(ctx context.Context) (*DeliveryAgency, error) {
	nodes, err := daq.Limit(1).All(setContextOp(ctx, daq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deliveryagency.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (daq *DeliveryAgencyQuery) FirstX(ctx context.Context) *DeliveryAgency {
	node, err := daq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeliveryAgency ID from the query.
// Returns a *NotFoundError when no DeliveryAgency ID was found.
func (daq *DeliveryAgencyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = daq.Limit(1).IDs(setContextOp(ctx, daq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deliveryagency.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (daq *DeliveryAgencyQuery) FirstIDX(ctx context.Context) int {
	id, err := daq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeliveryAgency entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeliveryAgency entity is found.
// Returns a *NotFoundError when no DeliveryAgency entities are found.
func (daq *DeliveryAgencyQuery) Only(ctx context.Context) (*DeliveryAgency, error) {
	nodes, err := daq.Limit(2).All(setContextOp(ctx, daq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deliveryagency.Label}
	default:
		return nil, &NotSingularError{deliveryagency.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (daq *DeliveryAgencyQuery) OnlyX(ctx context.Context) *DeliveryAgency {
	node, err := daq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeliveryAgency ID in the query.
// Returns a *NotSingularError when more than one DeliveryAgency ID is found.
// Returns a *NotFoundError when no entities are found.
func (daq *DeliveryAgencyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = daq.Limit(2).IDs(setContextOp(ctx, daq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deliveryagency.Label}
	default:
		err = &NotSingularError{deliveryagency.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (daq *DeliveryAgencyQuery) OnlyIDX(ctx context.Context) int {
	id, err := daq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeliveryAgencies.
func (daq *DeliveryAgencyQuery) All(ctx context.Context) ([]*DeliveryAgency, error) {
	ctx = setContextOp(ctx, daq.ctx, "All")
	if err := daq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DeliveryAgency, *DeliveryAgencyQuery]()
	return withInterceptors[[]*DeliveryAgency](ctx, daq, qr, daq.inters)
}

// AllX is like All, but panics if an error occurs.
func (daq *DeliveryAgencyQuery) AllX(ctx context.Context) []*DeliveryAgency {
	nodes, err := daq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeliveryAgency IDs.
func (daq *DeliveryAgencyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if daq.ctx.Unique == nil && daq.path != nil {
		daq.Unique(true)
	}
	ctx = setContextOp(ctx, daq.ctx, "IDs")
	if err = daq.Select(deliveryagency.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (daq *DeliveryAgencyQuery) IDsX(ctx context.Context) []int {
	ids, err := daq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (daq *DeliveryAgencyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, daq.ctx, "Count")
	if err := daq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, daq, querierCount[*DeliveryAgencyQuery](), daq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (daq *DeliveryAgencyQuery) CountX(ctx context.Context) int {
	count, err := daq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (daq *DeliveryAgencyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, daq.ctx, "Exist")
	switch _, err := daq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (daq *DeliveryAgencyQuery) ExistX(ctx context.Context) bool {
	exist, err := daq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeliveryAgencyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (daq *DeliveryAgencyQuery) Clone() *DeliveryAgencyQuery {
	if daq == nil {
		return nil
	}
	return &DeliveryAgencyQuery{
		config:       daq.config,
		ctx:          daq.ctx.Clone(),
		order:        append([]deliveryagency.OrderOption{}, daq.order...),
		inters:       append([]Interceptor{}, daq.inters...),
		predicates:   append([]predicate.DeliveryAgency{}, daq.predicates...),
		withProducts: daq.withProducts.Clone(),
		// clone intermediate query.
		sql:  daq.sql.Clone(),
		path: daq.path,
	}
}

// WithProducts tells the query-builder to eager-load the nodes that are connected to
// the "products" edge. The optional arguments are used to configure the query builder of the edge.
func (daq *DeliveryAgencyQuery) WithProducts(opts ...func(*ProductQuery)) *DeliveryAgencyQuery {
	query := (&ProductClient{config: daq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	daq.withProducts = query
	return daq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Country string `json:"country,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeliveryAgency.Query().
//		GroupBy(deliveryagency.FieldCountry).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (daq *DeliveryAgencyQuery) GroupBy(field string, fields ...string) *DeliveryAgencyGroupBy {
	daq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeliveryAgencyGroupBy{build: daq}
	grbuild.flds = &daq.ctx.Fields
	grbuild.label = deliveryagency.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Country string `json:"country,omitempty"`
//	}
//
//	client.DeliveryAgency.Query().
//		Select(deliveryagency.FieldCountry).
//		Scan(ctx, &v)
func (daq *DeliveryAgencyQuery) Select(fields ...string) *DeliveryAgencySelect {
	daq.ctx.Fields = append(daq.ctx.Fields, fields...)
	sbuild := &DeliveryAgencySelect{DeliveryAgencyQuery: daq}
	sbuild.label = deliveryagency.Label
	sbuild.flds, sbuild.scan = &daq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeliveryAgencySelect configured with the given aggregations.
func (daq *DeliveryAgencyQuery) Aggregate(fns ...AggregateFunc) *DeliveryAgencySelect {
	return daq.Select().Aggregate(fns...)
}

func (daq *DeliveryAgencyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range daq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, daq); err != nil {
				return err
			}
		}
	}
	for _, f := range daq.ctx.Fields {
		if !deliveryagency.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if daq.path != nil {
		prev, err := daq.path(ctx)
		if err != nil {
			return err
		}
		daq.sql = prev
	}
	return nil
}

func (daq *DeliveryAgencyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DeliveryAgency, error) {
	var (
		nodes       = []*DeliveryAgency{}
		_spec       = daq.querySpec()
		loadedTypes = [1]bool{
			daq.withProducts != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DeliveryAgency).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DeliveryAgency{config: daq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, daq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := daq.withProducts; query != nil {
		if err := daq.loadProducts(ctx, query, nodes,
			func(n *DeliveryAgency) { n.Edges.Products = []*Product{} },
			func(n *DeliveryAgency, e *Product) { n.Edges.Products = append(n.Edges.Products, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (daq *DeliveryAgencyQuery) loadProducts(ctx context.Context, query *ProductQuery, nodes []*DeliveryAgency, init func(*DeliveryAgency), assign func(*DeliveryAgency, *Product)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*DeliveryAgency)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Product(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(deliveryagency.ProductsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.delivery_agency_products
		if fk == nil {
			return fmt.Errorf(`foreign-key "delivery_agency_products" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "delivery_agency_products" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (daq *DeliveryAgencyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := daq.querySpec()
	_spec.Node.Columns = daq.ctx.Fields
	if len(daq.ctx.Fields) > 0 {
		_spec.Unique = daq.ctx.Unique != nil && *daq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, daq.driver, _spec)
}

func (daq *DeliveryAgencyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(deliveryagency.Table, deliveryagency.Columns, sqlgraph.NewFieldSpec(deliveryagency.FieldID, field.TypeInt))
	_spec.From = daq.sql
	if unique := daq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if daq.path != nil {
		_spec.Unique = true
	}
	if fields := daq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deliveryagency.FieldID)
		for i := range fields {
			if fields[i] != deliveryagency.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := daq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := daq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := daq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := daq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (daq *DeliveryAgencyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(daq.driver.Dialect())
	t1 := builder.Table(deliveryagency.Table)
	columns := daq.ctx.Fields
	if len(columns) == 0 {
		columns = deliveryagency.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if daq.sql != nil {
		selector = daq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if daq.ctx.Unique != nil && *daq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range daq.predicates {
		p(selector)
	}
	for _, p := range daq.order {
		p(selector)
	}
	if offset := daq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := daq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeliveryAgencyGroupBy is the group-by builder for DeliveryAgency entities.
type DeliveryAgencyGroupBy struct {
	selector
	build *DeliveryAgencyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dagb *DeliveryAgencyGroupBy) Aggregate(fns ...AggregateFunc) *DeliveryAgencyGroupBy {
	dagb.fns = append(dagb.fns, fns...)
	return dagb
}

// Scan applies the selector query and scans the result into the given value.
func (dagb *DeliveryAgencyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dagb.build.ctx, "GroupBy")
	if err := dagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeliveryAgencyQuery, *DeliveryAgencyGroupBy](ctx, dagb.build, dagb, dagb.build.inters, v)
}

func (dagb *DeliveryAgencyGroupBy) sqlScan(ctx context.Context, root *DeliveryAgencyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dagb.fns))
	for _, fn := range dagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dagb.flds)+len(dagb.fns))
		for _, f := range *dagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeliveryAgencySelect is the builder for selecting fields of DeliveryAgency entities.
type DeliveryAgencySelect struct {
	*DeliveryAgencyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (das *DeliveryAgencySelect) Aggregate(fns ...AggregateFunc) *DeliveryAgencySelect {
	das.fns = append(das.fns, fns...)
	return das
}

// Scan applies the selector query and scans the result into the given value.
func (das *DeliveryAgencySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, das.ctx, "Select")
	if err := das.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeliveryAgencyQuery, *DeliveryAgencySelect](ctx, das.DeliveryAgencyQuery, das, das.inters, v)
}

func (das *DeliveryAgencySelect) sqlScan(ctx context.Context, root *DeliveryAgencyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(das.fns))
	for _, fn := range das.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*das.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := das.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
