// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/deliveryagency"
	"backend/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeliveryAgencyDelete is the builder for deleting a DeliveryAgency entity.
type DeliveryAgencyDelete struct {
	config
	hooks    []Hook
	mutation *DeliveryAgencyMutation
}

// Where appends a list predicates to the DeliveryAgencyDelete builder.
func (dad *DeliveryAgencyDelete) Where(ps ...predicate.DeliveryAgency) *DeliveryAgencyDelete {
	dad.mutation.Where(ps...)
	return dad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dad *DeliveryAgencyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dad.sqlExec, dad.mutation, dad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dad *DeliveryAgencyDelete) ExecX(ctx context.Context) int {
	n, err := dad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dad *DeliveryAgencyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(deliveryagency.Table, sqlgraph.NewFieldSpec(deliveryagency.FieldID, field.TypeInt))
	if ps := dad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dad.mutation.done = true
	return affected, err
}

// DeliveryAgencyDeleteOne is the builder for deleting a single DeliveryAgency entity.
type DeliveryAgencyDeleteOne struct {
	dad *DeliveryAgencyDelete
}

// Where appends a list predicates to the DeliveryAgencyDelete builder.
func (dado *DeliveryAgencyDeleteOne) Where(ps ...predicate.DeliveryAgency) *DeliveryAgencyDeleteOne {
	dado.dad.mutation.Where(ps...)
	return dado
}

// Exec executes the deletion query.
func (dado *DeliveryAgencyDeleteOne) Exec(ctx context.Context) error {
	n, err := dado.dad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{deliveryagency.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dado *DeliveryAgencyDeleteOne) ExecX(ctx context.Context) {
	if err := dado.Exec(ctx); err != nil {
		panic(err)
	}
}
