version: "3.9"
services:
  nextjs_deployment:
    container_name: nextjs
    image: 679oose/nextjs_deployment:latest
    restart: always
    ports:
      - "80:3000"
    environment:
      TZ: "Asia/Seoul"

  fibergo_deployment:
    container_name: fibergo
    image: 679oose/fiber_go_deployment:latest
    restart: always
    ports:
      - "8080"
    environment:
      TZ: "Asia/Seoul"
      ProductionLevel: "production"
