// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DeliveryAgenciesColumns holds the columns for the "delivery_agencies" table.
	DeliveryAgenciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "country", Type: field.TypeString},
		{Name: "vat_reduction_rate", Type: field.TypeFloat64},
		{Name: "shipping_fee", Type: field.TypeJSON},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DeliveryAgenciesTable holds the schema information for the "delivery_agencies" table.
	DeliveryAgenciesTable = &schema.Table{
		Name:       "delivery_agencies",
		Columns:    DeliveryAgenciesColumns,
		PrimaryKey: []*schema.Column{DeliveryAgenciesColumns[0]},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "brand", Type: field.TypeString},
		{Name: "product_name", Type: field.TypeString},
		{Name: "product_img_url", Type: field.TypeString},
		{Name: "product_url", Type: field.TypeString},
		{Name: "price_currency", Type: field.TypeString},
		{Name: "retail_price", Type: field.TypeFloat64},
		{Name: "sale_price", Type: field.TypeFloat64},
		{Name: "kor_brand", Type: field.TypeString, Nullable: true},
		{Name: "kor_product_name", Type: field.TypeString, Nullable: true},
		{Name: "product_id", Type: field.TypeString, Nullable: true},
		{Name: "gender", Type: field.TypeString, Nullable: true},
		{Name: "color", Type: field.TypeString, Nullable: true},
		{Name: "category", Type: field.TypeString, Nullable: true},
		{Name: "category_spec", Type: field.TypeString, Nullable: true},
		{Name: "sold_out", Type: field.TypeBool, Default: false},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "store_name", Type: field.TypeString, Nullable: true},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "products_stores_product",
				Columns:    []*schema.Column{ProductsColumns[17]},
				RefColumns: []*schema.Column{StoresColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "product_product_name_product_url",
				Unique:  true,
				Columns: []*schema.Column{ProductsColumns[2], ProductsColumns[4]},
			},
		},
	}
	// StoresColumns holds the columns for the "stores" table.
	StoresColumns = []*schema.Column{
		{Name: "store_name", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "country", Type: field.TypeString},
		{Name: "currency", Type: field.TypeString},
		{Name: "tax_reduction", Type: field.TypeFloat64},
		{Name: "intl_shipping_fee", Type: field.TypeJSON},
		{Name: "intl_free_shipping_fee", Type: field.TypeInt},
		{Name: "domestic_shipping_fee", Type: field.TypeFloat64},
		{Name: "domestic_free_shipping_fee", Type: field.TypeFloat64},
		{Name: "shipping_fee_cumulation", Type: field.TypeBool},
		{Name: "delivery_agency", Type: field.TypeString},
		{Name: "broker_fee", Type: field.TypeBool},
		{Name: "ddp", Type: field.TypeBool},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// StoresTable holds the schema information for the "stores" table.
	StoresTable = &schema.Table{
		Name:       "stores",
		Columns:    StoresColumns,
		PrimaryKey: []*schema.Column{StoresColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DeliveryAgenciesTable,
		ProductsTable,
		StoresTable,
	}
)

func init() {
	ProductsTable.ForeignKeys[0].RefTable = StoresTable
}
