// Generated by https://quicktype.io

export interface Product {
  id: number
  store_name: string
  brand: string
  product_name: string
  product_img_url: string
  product_url: string
  currency_code: string
  retail_price: number
  sale_price: number
  product_id: string
  color: string
  updated_at: string
  edges: Edges
}

export interface Edges {}
